// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8P_ysCIXqNEd07q5zegirRWg9c4wGmY',
    appId: '1:680575945682:web:8a2074b6884789c53ad60b',
    messagingSenderId: '680575945682',
    projectId: 'loginfirebase-f2780',
    authDomain: 'loginfirebase-f2780.firebaseapp.com',
    storageBucket: 'loginfirebase-f2780.firebasestorage.app',
    measurementId: 'G-8Q0PLM7YYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqqMngsshMo9c1ZR8V2fe5bMtbm7_dTCg',
    appId: '1:680575945682:android:28ca14eb5dcf69c43ad60b',
    messagingSenderId: '680575945682',
    projectId: 'loginfirebase-f2780',
    storageBucket: 'loginfirebase-f2780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGK1EzR_TmEdiXy1yPHU-FIfR5fvjsJ70',
    appId: '1:680575945682:ios:9a1c8d2de311325b3ad60b',
    messagingSenderId: '680575945682',
    projectId: 'loginfirebase-f2780',
    storageBucket: 'loginfirebase-f2780.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGK1EzR_TmEdiXy1yPHU-FIfR5fvjsJ70',
    appId: '1:680575945682:ios:9a1c8d2de311325b3ad60b',
    messagingSenderId: '680575945682',
    projectId: 'loginfirebase-f2780',
    storageBucket: 'loginfirebase-f2780.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8P_ysCIXqNEd07q5zegirRWg9c4wGmY',
    appId: '1:680575945682:web:47b5104bc204e53c3ad60b',
    messagingSenderId: '680575945682',
    projectId: 'loginfirebase-f2780',
    authDomain: 'loginfirebase-f2780.firebaseapp.com',
    storageBucket: 'loginfirebase-f2780.firebasestorage.app',
    measurementId: 'G-CNDBC5JYJQ',
  );
}
